class AppRoute {
  static const String login = "/login" ;
  static const String onBoarding = "/onBoarding";
  static const String signUp = "/signup";
  static const String ForgetPassword = "/forgetpassword";
  static const String VeryfiyCode = "/veryfiycode";
  static const String ResetPassword = "/resetpassword";
  static const String successSignUp = "/successsignup";
  static const String successResetPassword = "/successresetpassword";
  static const String checkEmail = "/checkemail";
  static const String verfiyCodeSignUp = "/verfiycodesignup";
  static const String homeScreen = "/homescreen";
  static const String itemsScreen = "/items";
  static const String productdetails = "/productdetails";
  static const String myFavorite = "/myfavorite";
  static const String homeTest  = "/hometest";
  static const String cart  = "/cart";
  static const String addressView  = "/addressview";
  static const String addressAdd  = "/addressadd";
  static const String addressAddDetails  = "/addressadddetails";
  static const String checkout  = "/checkout";
  static const String ordersArchive  = "/ordersarchive";
  static const String ordersPending  = "/orderspending";
  static const String chooseLang  = "/chooselang";
  static const String prodettest  = "/prodettest";
  static const String ordersDetails  = "/ordersdetails";
  static const String offersScreen  = "/offersscreen";
  static const String ordersTracking  = "/ordertracking";
}